Fix call indentation for chained functions
silvermine/eslint-plugin-silvermine pull request #13
Opened 2017-03-09 22:26 UTC by jimjenkins5

Chained function calls were throwing errors because the node location is the start of the parent call.  and this is what I was using to check whether the first argument was on a new line.

Example:
```
promise
   .then(function(res) {
      return something;
   });
```
Would throw an error because `res` is not on the same line as `promise`, so the parenthesis at the end would need to be on it's own line.  

I fixed this by checking the position of `node.callee.property`, which in the above example is `then`, if it exists, and `node.callee` if it does not.

2017-03-09 22:34 UTC, jthomerson requested changes

2017-03-09 22:34 UTC, jthomerson commented on tests/lib/rules/call-indentation.test.js
> +   '      somthing()',
something

2017-03-09 22:49 UTC, jimjenkins5 commented on tests/lib/rules/call-indentation.test.js
> +   '      somthing()',
fixed

2017-03-10 02:28 UTC, jthomerson approved these changes

2017-03-10 02:28 UTC, merged