New rules for empty object and array spacing
silvermine/eslint-plugin-silvermine pull request #7
Opened 2017-02-06 20:52 UTC by jimjenkins5

This commit adds 2 new rules. One for spacing in empty objects and one for spacing in empty arrays.

This addresses one of the issues found in https://github.com/silvermine/serverless-plugin-external-sns-events/issues/10

2017-02-12 15:05 UTC, jthomerson requested changes

2017-02-12 15:05 UTC, jthomerson commented on tests/lib/rules/empty-array-spacing.test.js
> + * @fileoverview Ensure consitent spacing in empty object declarations
spelling: consistent

2017-02-12 15:05 UTC, jthomerson commented on tests/lib/rules/empty-object-spacing.test.js
> + * @fileoverview Ensure consitent spacing in empty object declarations
spelling

2017-02-17 03:44 UTC, jthomerson commented
@jimjenkins5 this one is still pending changes. Please rebase now that #8 has been merged so that we can get the build verification on it.

2017-02-17 12:56 UTC, jimjenkins5 commented on tests/lib/rules/empty-object-spacing.test.js
> + * @fileoverview Ensure consitent spacing in empty object declarations
fixed

2017-02-17 12:56 UTC, jimjenkins5 commented on tests/lib/rules/empty-array-spacing.test.js
> + * @fileoverview Ensure consitent spacing in empty object declarations
fixed

2017-02-21 13:57 UTC, merged