Travis Configuration
silvermine/eslint-plugin-silvermine pull request #8
Opened 2017-02-07 18:41 UTC by jimjenkins5

Builds were failing because we had no travis configuration file.

This PR adds a .travis.yml file with the configuration to run grunt (eslint) and npm test

2017-02-12 15:00 UTC, jthomerson requested changes

2017-02-12 15:00 UTC, jthomerson commented on .travis.yml
> +   - grunt
Please make this more specific, e.g. `grunt standards`, so that it's easier to tell what's happening on Travis

2017-02-13 13:58 UTC, jimjenkins5 commented on .travis.yml
> +   - grunt
fixed

2017-02-17 03:41 UTC, jthomerson approved these changes

2017-02-17 03:42 UTC, merged